name: Upload AI Insights to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib openpyxl google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      - name: Create service account key file
        run: |
          echo "${{ secrets.GCP_SA_JSON }}" | base64 --decode > sa_key.json

      - name: Generate and upload AI Insights file
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python - <<'PY'
          import json, os, pandas as pd
          from datetime import datetime
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          from googleapiclient.http import MediaFileUpload

          # --- 1. Generate Insights content ---
          week = 42
          data = {
              "Week": [week],
              "Narrative": [f"SLA performance remained stable for week {week}. FRT improved slightly, maintaining targets."]
          }
          df = pd.DataFrame(data)
          file_name = f"AI_Insights_Week_{week}.html"
          df.to_html(file_name, index=False)

          print(f"✅ File generated: {file_name}")

          # --- 2. Upload to Google Drive ---
          folder_id = os.getenv("GDRIVE_FOLDER_ID")
          creds = service_account.Credentials.from_service_account_file(
              "sa_key.json",
              scopes=["https://www.googleapis.com/auth/drive.file"]
          )
          service = build("drive", "v3", credentials=creds)

          file_metadata = {"name": file_name, "parents": [folder_id]}
          media = MediaFileUpload(file_name, mimetype="text/html")

          uploaded = service.files().create(
              body=file_metadata, media_body=media, fields="id"
          ).execute()

          print(f"✅ Uploaded to Drive with ID: {uploaded.get('id')}")
          PY
